### PR TITLE
Issue 176 - Error stack derivation for `profileName` causing OOM crashes

### LINKED ISSUE #176: getDefaultProfileName side effects
The `getDefaultProfileName` call that is made when a name is not passed to the moize constructor was consistently triggering out of memory errors in an app I'm working on.  Digging into the problem, I discovered that the `new Error().stack` [call](https://github.com/planttheidea/moize/blob/6ae4576f492cd78b5dac4fcc9910e0bd63705563/src/stats.ts#L95) inside that method has a bunch of non-obvious side effects.  The most significant is fetching, parsing and sorting the source map related to the caller.  Something about doing that in a dev environment was trigging OOM (possibly due to reloads).  For reference, the particular source map for our bundled app is about 14mb.

Of course, the easy solution is to just pass a `profileName` in the [options](https://www.npmjs.com/package/moize#profilename) for the constructor.  However, it might be a good idea to mention this in the docs which are a bit misleading when they say "You must be collecting statistics for this option to take effect."  That is, there is definitely an effect of passing this option even if stats are not collected.

### PR DESCRIPTION
**Pull request by planttheidea**
## Reason for change

The derivation of a default `profileName` involved creating a dummy error and inspecting the stack trace. This was meant to provide additional context about the original function call, in case it was a name shared with other functions or an anonymous function. However, this introspection can have potentially serious costs for projects that have large source maps, and can cause OOM crashes (seen in #176 ).

## Change

Remove the use of the dummy error stack entirely, instead simply using the original tiered value alone:

- If `displayName` property exists, use it
- Else if `name` property is populated, use it
- Else use `Anonymous` plus an internal counter to separate multiple anonymous functions

The use of the dummy error and stack introspection was never a documented feature, so I'm not considering this a breaking change.

### CODE REVIEW

File: src/stats.ts [hunk 1]
```diff
@@ -92,35 +92,11 @@ export function createOnCacheHitIncrementCallsAndHits(options: Options) {
 export function getDefaultProfileName(
     fn: Fn | FunctionalComponent<Record<string, unknown>>
 ) {
-    const stack = new Error().stack;
```
Comment (planttheidea) [inline src/stats.ts:95]: The use of `stack` was always meant to provide some additional context as to the original function, however the additional context is not worth the potential memory consumption cost created.

File: README.md [hunk 2]
```diff
@@ -780,6 +781,20 @@ const fn = (one: string, two: string) => `${one} ${two}`;
 export default moize.maxSize(5)(fn);
 ```
 
+## moize.profile
```
Comment (planttheidea) [inline README.md:784]: It seems this was missing in the existing documentation, so I've added it for completeness.

**Review by scottned — APPROVED** [review]
